name: ShowDamage
main: strimy.bukkit.plugins.showdamage.ShowDamageManager
version: 1.0rc1

commands:
    showdamage: 
        description: Configure the ShowDamage plugin
        usage: /showdamage enable|disable