name: ShowDamage
main: strimy.bukkit.plugins.showdamage.ShowDamage
version: 1.1

commands:
    showdamage: 
        description: Configure the ShowDamage plugin
        usage: /showdamage enable|disable